#ifndef SISCI_PERF_INITIATOR_MAIN_H
#define SISCI_PERF_INITIATOR_MAIN_H

#define MAX_PEERS 4

#define SISCI_PERF_PIO 1
#define SISCI_PERF_DMA 1
#define SISCI_PERF_SCALE_UP 1
#define SISCI_PERF_SCALE_OUT 1
#define SISCI_PERF_VAR_SIZE 1
#define SISCI_PERF_VAR_SIZE_DMA 1
#define SISCI_PERF_DMA_VEC 1
#define SISCI_PERF_INT 1
#define SISCI_PERF_DATA_INT 1
#define SISCI_PERF_PING_PONG_PIO 1
#define SISCI_PERF_BROADCAST_PIO 1

#endif //SISCI_PERF_INITIATOR_MAIN_H
